apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dispatcher.secretName" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
type: Opaque
data:
  postgres-username: {{ include "dispatcher.dbUsername" . | b64enc }}
  postgres-password: {{ randAlphaNum 32 | b64enc }}